#!/bin/sh
#DATE=$(date '+ %a  %H:%M')
DATE=$(date '+  %A, %d/%m') 
TIME=$(date '+ %H:%M')
# DATE=$(date '+   %d/%m')
DATE_TIME="$DATE $TIME"
echo $DATE_TIME

case $BLOCK_BUTTON in
    1) gsimplecal  & "$@" > /dev/null ;;
#    1) yad --no-buttons --geometry=+$X+20 --class "yad_cal" --calendar ;;
    2) chromium  --profile-directory=Default --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki  & "$@" > /dev/null ;;
    3) chromium --profile-directory=Default --app-id=ejjicmeblgpmajnghnpcppodonldlgfn  & "$@" > /dev/null ;; 
esac 
