#!/bin/sh
#DATE=$(date '+ %a  %H:%M')
TIME=$(date '+ %H:%M:%S  ')
DATE=$(date '+   %d/%m')
DATE_TIME="$TIME...$DATE"
echo $DATE_TIME

case $BLOCK_BUTTON in
    1) gsimplecal  & "$@" > /dev/null ;;
#    1) yad --no-buttons --geometry=+$X+20 --class "yad_cal" --calendar ;;
    2) chromium  --profile-directory=Default --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki  & "$@" > /dev/null ;;
    3) chromium --profile-directory=Default --app-id=ejjicmeblgpmajnghnpcppodonldlgfn  & "$@" > /dev/null ;; 
esac 
