#!/bin/bash

sudo pacman -S vim
sudo pacman -S emacs
sudo pacman -S tmux
sudo pacman -S curl
sudo pacman -S python2-neovim python-neovim

# Installing yaourt for future
cd "/tmp/"
curl -L -O "https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz"
curl -L -O "https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz"
tar -xvf package-query.tar.gz
cd "package-query"
makepkg -sri
cd ..
tar -xvf yaourt.tar.gz
cd "yaourt"
makepkg -sri

# Fonts
yaourt --noconfirm adobe-source-sans-pro-fonts
yaourt --noconfirm ttf-font-awesome
yaourt --noconfirm ttf-font-icons
yaourt --noconfirm ttf-inconsolata
yaourt --noconfirm ttf-dejavu
yaourt --noconfirm powerline-fonts-git
yaourt --noconfirm adobe-source-han-sans-jp-fonts
yaourt --noconfirm otf-source-han-code-jp

# Sound/Music
yaourt --noconfirm alsa-utils
yaourt --noconfirm alsaplayer
yaourt --noconfirm apulse
yaourt --noconfirm pamixer

yaourt --noconfirm mopidy
yaourt --noconfirm mopidy-spotify
yaourt --noconfirm ncmpcpp
yaourt --noconfirm spotify

# Video
yaourt --noconfirm vlc

# Internet
yaourt --noconfirm deluge
yaourt --noconfirm google-chrome-dev
yaourt --noconfirm insync
yaourt --noconfirm iputils

# Coding
yaourt --noconfirm gdb
yaourt --noconfirm neovim
yaourt --noconfirm meld
yaourt --noconfirm ycm-generator

# WM
yaourt --noconfirm i3-gaps
yaourt --noconfirm i3-blocks
yaourt --noconfirm j4-dmenu-desktop
yaourt --noconfirm nitrogen

# Utility
yaourt --noconfirm p7zip
yaourt --noconfirm ranger
yaourt --noconfirm shutter
yaourt --noconfirm skype
yaourt --noconfirm synergy
yaourt --noconfirm update-pacman-mirrorlist
yaourt --noconfirm rsync
yaourt --noconfirm arandr

# Misc
yaourt --noconfirm archey3
yaourt --noconfirm htop
yaourt --noconfirm keychain
yaourt --noconfirm openssh
yaourt --noconfirm highlight
yaourt --noconfirm poppler
yaourt --noconfirm mediainfo
yaourt --noconfirm xtitle
yaourt --noconfirm w3m


# pkgfile getting stuff
yaourt --noconfirm pkgfile
sudo pkgfile --update

# This is for nvim to get same plugins as vim
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim
