#!/bin/bash

install_dir="$HOME/.bin"
neovim_install="$install_dir/neovim"
python3_install="$install_dir/python3.5"

echo "Installing in $install_dir"
mkdir $install_dir
cd $install_dir

touch $HOME/.zshrc

install_neovim() 
{
  cd $install_dir
  # Installing Neovim
  echo "Installing Neovim in $neovim"
  echo "Warning... This will take a while"
  sleep 2
  git clone https://github.com/neovim/neovim neovim-git
  cd neovim-git
  rm -rf build
  echo "Starting building"
  sleep 2
  make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$neovim"

  echo "Starting installing"
  sleep 2
  make install

  cd ..
  rm -rf neovim-git
  echo "Done installing Neovim"
}

setup_zshrc()
{
  echo "Adding export to ~/.zshrc"
  if ! grep -q  "export PATH=\"\$HOME/.bin/neovim/bin:\$PATH\"" "$HOME/.zshrc"; then
    echo "export PATH=\"\$HOME/.bin/neovim/bin:\$PATH\"" >> ~/.zshrc
  fi

  echo "Adding vim=nvim alias to ~/.zshrc"
  if ! grep -q  "alias vim=nvim" "$HOME/.zshrc"; then
    echo "alias vim=nvim" >> ~/.zshrc
  fi

  echo "Adding python path to ~/.zshrc"
  if ! grep -q  "export PATH=\"$HOME/.bin/.python3.5/bin:$PATH\"" "$HOME/.zshrc"; then
    echo "export PATH=\"$HOME/.bin/.python3.5/bin:$PATH\"" >> ~/.zshrc
  fi

  source ~/.zshrc
}

setup_neovim() 
{
  # First, the plugin manager
  mkdir ~/.config
  mkdir -p ~/.vim/backup
  touch ~/.vimrc
  ln -s ~/.vim ~/.config/nvim
  ln -s ~/.vimrc ~/.config/nvim/init.vim
}

setup_vimrc()
{
  # Setting up the vimrc
  echo "Setting up basic vimrc"
  echo "
  function! DoRemote(arg)
    UpdateRemotePlugins
  endfunction

  call plug#begin('~/.vim/plug')
  \" Syntax checking/autocomplete plugins
  \" Async Autocompletion
  Plug 'Shougo/deoplete.nvim', {'do': function('DoRemote')}
  \" C
  Plug 'zchee/deoplete-clang'
  Plug 'neomake/neomake'
  Plug 'ervandew/supertab'

  \" File finder
  Plug 'ctrlpvim/ctrlp.vim'

  \" Class outline viewer
  Plug 'majutsushi/tagbar'

  \" Solarized colour theme
  Plug 'altercation/vim-colors-solarized'

  \" Super neato looking bar at the bottom
  Plug 'bling/vim-airline'

  \" Surround, bracket functionality
  Plug 'tpope/vim-surround'

  call plug#end()

  \" Basic Vim Settings
  set t_Co=256
  set background=dark
  let g:solarized_termtrans = 1
  colorscheme solarized

  set modeline
  set smartindent
  set tabstop=2                                 \" Tab key results in 2 spaces
  set shiftwidth=2                              \" The num of spaces for indenting
  set backspace=indent,eol,start
  set softtabstop=2                             \" Tab key results in 2 spaces
  set expandtab                                 \" Expand tabs to spaces
  set clipboard+=unnamed
  set clipboard+=unnamedplus
  set go+=a
  set number                                    \" Enable line numbers
  set laststatus=2                              \" Always show statusline
  set nofoldenable
  set hlsearch                                  \" Highlight all search hits
  set spell                                     \" Enable spell checking

  set autochdir

  \" Backup
  set noswapfile
  set backupdir=~/.vim/backup

  let g:airline_powerline_fonts = 1

  \" Deoplete
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#sources#clang#libclang_path='/usr/lib/i386-linux-gnu/libclang.so.1'
  let g:deoplete#sources#clang#clang_header='/usr/lib/clang'
  let g:deoplete#sources#clang#flags=['-O2', '-Wall', '-Werror']

  \" Map f8 for Tagbar
  nmap <F8> :TagbarToggle<CR>

  \" Map enter to clear highlighted search hits
  nnoremap <CR> :nohlsearch<CR><CR>

  \" Neomake autorun
  autocmd! BufEnter,BufWritePost * Neomake
  let g:neomake_cpp_enabled_makers = ['clang']
  let g:neomake_cpp_clang_maker = {
     \ 'exe': 'clang++',
     \ 'args': ['-O2', '-Wall', '-Werror'],
     \ }
  " > ~/.vimrc

  echo "Vimrc is done"
}

install_plugins()
{
  echo "Installing vim plug"
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  echo "Installing Plugins"
  vim +PlugInstall +qall
}

install_python3()
{
  wget "https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz"
  tar xf Python-3.5.2.tgz
  cd Python-3.5.2
  ./configure --prefix=$python3_install
  make
  make install
  cd ..
  rm -rf Python-3.5.2 Python-3.5.2.tgz

  pip3 install --user neovim
}

install_neovim;
setup_zshrc;
setup_neovim;
setup_vimrc;
install_plugins;
